import {REPUBLIC_LOGO} from "./republicLogo";
import {CastleWeather} from "./CastleWeather";
import {returnToCastleHome} from "./castleWindow";
import {callable} from "@decky/api";
import {useEffect,useRef,useState,useId} from "react";
import {BatteryGlyph,GameArt,Icon,IconName,MenuView,themeMenu,useHome,useMenu} from "../common";
import {Press,Stage,ThemeRoot,useStage} from "../input";
import {fmtLastPlayed,openSteam} from "../library";
import {fmtTime,playSound,useBattery,useClock,useSteamStatus} from "../steam";
import {THEMES,updateSettings} from "../settings";
import {CINEMATIC_CSS} from "./cinematicStyles";
const getMedia=callable<[string],{video?:string;poster?:string}>("cinematic_assets");
function Background({kind,paused}:{kind:string;paused:boolean}){
 const ref=useRef<HTMLVideoElement>(null);const [assets,setAssets]=useState<{video?:string;poster?:string}>({});
 useEffect(()=>{let alive=true;if((window as any).__testAssets){setAssets({video:`../bundle/cinematic/${kind}.mp4`,poster:`../bundle/cinematic/${kind}.jpg`});}else getMedia(kind).then(a=>alive&&setAssets(a)).catch(()=>{});return()=>{alive=false;};},[kind]);
 useEffect(()=>{const video=ref.current;if(!video)return;const media=window.matchMedia("(prefers-reduced-motion: reduce)");let intersecting=true;const sync=()=>{if(paused||document.hidden||media.matches||!intersecting)video.pause();else video.play().catch(()=>{});};const observer=new IntersectionObserver(e=>{intersecting=e[0]?.isIntersecting??false;sync();});observer.observe(video);document.addEventListener("visibilitychange",sync);media.addEventListener("change",sync);video.addEventListener("loadeddata",sync);sync();return()=>{video.pause();observer.disconnect();document.removeEventListener("visibilitychange",sync);media.removeEventListener("change",sync);video.removeEventListener("loadeddata",sync);};},[paused,assets.video]);
 return <video ref={ref} className="cinema-video" src={assets.video} poster={assets.poster} muted loop playsInline preload="auto" aria-hidden="true"/>;
}
function GlassEdge({profile=false}:{profile?:boolean}){return <svg className="glass-edge" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polygon points={profile?"6,0.5 99.5,0.5 99.5,87 94,99.5 6,99.5 .5,87 .5,13":".5,.5 96,.5 99.5,9 99.5,91 96,99.5 .5,99.5"} fill="none" stroke="white" strokeOpacity=".8" strokeWidth="1" vectorEffect="non-scaling-stroke"/></svg>}
function RepublicMark(){return <svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="46" fill="none" stroke="currentColor" strokeWidth="3"/><circle cx="50" cy="50" r="39" fill="none" stroke="currentColor" strokeWidth="2"/>{Array.from({length:8},(_,i)=><path key={i} d="M50 13 L57 39 L68 50 L54 56 L50 84 L44 57 L30 50 L43 43 Z" transform={`rotate(${i*45} 50 50)`} fill="currentColor" opacity=".65"/>)}<circle cx="50" cy="50" r="42" fill="none" stroke="#a6853e" strokeWidth="3" strokeDasharray="24 9"/></svg>}

function Globe(){const id=useId().replace(/:/g,"");return <svg className="republic-globe" viewBox="0 0 200 190" aria-hidden="true"><defs><clipPath id={`globe-clip-${id}`}><circle cx="100" cy="90" r="72"/></clipPath><linearGradient id={`globe-beam-${id}`} x1="0" y1="0" x2="0" y2="1"><stop stopColor="#58aaff00"/><stop offset=".75" stopColor="#9ee5ff55"/><stop offset=".95" stopColor="#e0faffdd"/><stop offset="1" stopColor="#53baff00"/></linearGradient><pattern id={`globe-scan-${id}`} width="4" height="4" patternUnits="userSpaceOnUse"><path d="M0 1H4" stroke="#bcecff" strokeOpacity=".35" strokeWidth=".65"/></pattern><radialGradient id={`city-globe-${id}`}><stop stopColor="#163c6380"/><stop offset=".8" stopColor="#3186db30"/><stop offset="1" stopColor="#9dd8ff99"/></radialGradient></defs><ellipse cx="100" cy="151" rx="91" ry="12" fill="none" stroke="#438dc966"/><circle cx="100" cy="90" r="72" fill={`url(#city-globe-${id})`} stroke="#8cd1ff"/><g className="globe-longitudes">{[24,46,63].map(r=><ellipse key={r} cx="100" cy="90" rx={r} ry="72" fill="none" stroke="#7ac3ff55"/>)}</g>{[45,68,90,112,135].map(y=><path key={y} d={`M35 ${y} Q100 ${y+16} 165 ${y}`} fill="none" stroke="#7ac3ff55"/>)}<g className="globe-city">{Array.from({length:24},(_,i)=><path key={i} d={`M${39+i*5} 145 v-${12+(i*17)%66} h3 v${12+(i*17)%66}`} fill="#67b8ff33" stroke="#93d7ff77" strokeWidth=".5"/>)}<path d="M95 143 V65 L98 56 L100 33 L103 57 L108 68 V143" fill="#7ebeff55" stroke="#c5ebffaa"/></g><circle className="globe-holo-scan" cx="100" cy="90" r="72" fill={`url(#globe-scan-${id})`}/><g clipPath={`url(#globe-clip-${id})`}><rect className="globe-holo-beam" x="27" y="-30" width="146" height="38" fill={`url(#globe-beam-${id})`}/></g><ellipse className="globe-orbit" cx="100" cy="151" rx="91" ry="12" fill="none" stroke="#a6dfff" strokeWidth="1.2" strokeDasharray="18 270 8 270"/></svg>}
export function CinematicHome({kind}:{kind:"castle"|"republic"}){
 const api=useHome(),s=api.settings,{W,H}=useStage(),menu=useMenu(),now=useClock(15000),battery=useBattery(),status=useSteamStatus();
 const games=api.lib.games;const [sel,setSel]=useState(0),[nav,setNav]=useState(0),[zone,setZone]=useState<"nav"|"games"|"hero"|"quick">("games");const selected=Math.min(sel,Math.max(0,games.length-1)),g=games[selected];const row=useRef<HTMLDivElement>(null);const navRef=useRef<HTMLElement>(null);const [navVisible,setNavVisible]=useState(true);
 useEffect(()=>{const node=navRef.current;if(kind!=="castle"||!node)return;const disabled=!s.animations||window.matchMedia("(prefers-reduced-motion: reduce)").matches;const motion=node.animate(navVisible?[{transform:"translateY(-125%)"},{transform:"translateY(0)"}]:[{transform:"translateY(0)"},{transform:"translateY(-125%)"}],{duration:disabled?0:200,easing:"ease",fill:"forwards"});return()=>motion.cancel();},[navVisible,kind,s.animations]);
 useEffect(()=>{row.current?.querySelector('[data-selected="true"]')?.scrollIntoView({block:"nearest",inline:"nearest",behavior:s.animations?"smooth":"auto"});},[selected,s.animations]);
 const entries:{label:string;icon:IconName;run:()=>void}[]=[{label:"Home",icon:"home",run:()=>{if(kind==="castle")returnToCastleHome();setZone("games");setNav(0);}},{label:"Library",icon:"library",run:()=>openSteam("library")},...(kind==="castle"?[{label:"Store",icon:"store" as IconName,run:()=>openSteam("store")},{label:"Friends",icon:"friends" as IconName,run:()=>openSteam("friends")}]:[]),{label:"Downloads",icon:"download",run:()=>openSteam("downloads")},{label:"Settings",icon:"gear",run:()=>openSteam("settings")}];
 const launch=()=>{if(g)api.activate(g,()=>api.launch(g));};
 const options=()=>menu.open([{label:"Play",disabled:!g,action:launch},{label:"Game Details",disabled:!g,action:()=>g&&api.details(g)},{label:"Video background",sub:()=>[{label:"On",checked:s.videoBackgrounds[kind]!==false,action:()=>updateSettings(v=>({videoBackgrounds:{...v.videoBackgrounds,[kind]:true}}))},{label:"Off",checked:s.videoBackgrounds[kind]===false,action:()=>updateSettings(v=>({videoBackgrounds:{...v.videoBackgrounds,[kind]:false}}))}]},...(kind==="castle"?[{label:"Top-right display",sub:()=>[{label:"Deck status",checked:!s.castleWeather,action:()=>updateSettings({castleWeather:false})},{label:"Weather · auto location · °C",checked:s.castleWeather,action:()=>updateSettings({castleWeather:true})}]},{label:"Window presentation",sub:()=>[{label:"Replace home panels",checked:s.castleWindows!=="layered",action:()=>updateSettings({castleWindows:"replace"})},{label:"Layered glass windows",checked:s.castleWindows==="layered",action:()=>updateSettings({castleWindows:"layered"})}]}]:[]),{label:"Presets",sub:()=>themeMenu(s.theme,api.switchTheme,THEMES)},{label:"Home Screen Settings",action:api.openSettings}],kind==="castle"?"Floating Castle":"Galactic Republic");
 const onInput=(p:Press)=>{if(menu.handle(p))return true;if(kind==="castle"&&p.btn==="down"&&!navVisible){setNavVisible(true);setZone("nav");playSound("menu");return true;}if(kind==="castle"&&p.btn==="up"&&zone==="nav"&&nav===0){setNavVisible(false);setZone("games");playSound("close");return true;}if(p.btn==="y"||p.btn==="menu"){options();return true;}if(p.btn==="b"){setZone("nav");setNavVisible(true);setNav(0);return true;}if(zone==="nav"||zone==="quick"){if(p.btn==="up"||p.btn==="down")setNav(Math.max(0,Math.min(entries.length-1,nav+(p.btn==="up"?-1:1))));else if(p.btn==="right")setZone("games");else if(p.btn==="a")entries[nav].run();}else{if(p.btn==="left"){if(!selected)setZone("nav");else setSel(selected-1);}else if(p.btn==="right")setSel(Math.min(Math.min(games.length,60)-1,selected+1));else if(p.btn==="up")setZone(kind==="castle"&&zone!=="hero"?"hero":"nav");else if(p.btn==="down")setZone("games");else if(p.btn==="a")launch();}playSound("move");return true;};
 return <ThemeRoot onInput={onInput} hints={{a:"Select",b:"Back",y:"Options"}}><Stage background={kind==="castle"?"#80b8de":"#020911"}><div className={`cinema ${kind}`} data-motion={s.animations} data-summoned={api.busy} data-window-mode={s.castleWindows} style={{width:1280,height:720,transform:`scale(${W/1280},${H/720})`,transformOrigin:"top left"}}><style>{CINEMATIC_CSS}</style><Background kind={kind} paused={!s.animations||s.videoBackgrounds[kind]===false||api.busy}/><div className="cinema-shade"/>
 <header className="cinema-brand">{kind==="republic"?<><span className="republic-logo-orbit" role="img" aria-label="Galactic Republic emblem"><span className="republic-logo-volume">{Array.from({length:7},(_,i)=><span key={i} className="republic-supplied-logo" style={{maskImage:`url(${REPUBLIC_LOGO})`,WebkitMaskImage:`url(${REPUBLIC_LOGO})`,transform:`translateZ(${i-3}px)`,background:i===0||i===6?"linear-gradient(130deg,#fff0ac,#cca449 45%,#a97d27 70%,#f5d984)":"#88631f"}}/>)}</span></span><div>GALACTIC REPUBLIC<small>FOR A BRIGHTER TOMORROW</small></div></>:<div className="cardinal-brand">Cardinal System<small>access granted</small><small className="network-readout">CURRENT PORT: 8081<br/>IP ADDRESS: 2001:0DB8:AC10:FE01::</small></div>}</header>
 <div className="cinema-status">{kind==="castle"&&s.castleWeather?<CastleWeather/>:<><button aria-label="Search" onClick={()=>openSteam("search")}><Icon name="search" size={22}/></button><button aria-label="Notifications" onClick={()=>openSteam("notifications")}><Icon name="bell" size={21}/></button><Icon name="wifi" size={22}/>{battery&&<><span>{Math.round(battery.level*100)}%</span><BatteryGlyph level={battery.level} charging={battery.charging}/></>}<time>{fmtTime(now,s.clock24)}</time></>}</div>
 <nav ref={navRef} className="cinema-nav" aria-hidden={kind==="castle"&&!navVisible} style={{pointerEvents:kind==="castle"&&!navVisible?"none":undefined}}>{entries.map((e,i)=><button key={e.label} data-selected={nav===i} onClick={()=>{setNav(i);e.run();}}><span><Icon name={e.icon} size={kind==="castle"?30:23}/></span>{e.label}</button>)}</nav>
 {kind==="republic"?<><aside className="republic-info"><Globe/><strong>CORUSCANT</strong><small>CAPITAL OF THE REPUBLIC</small><blockquote>“ UNITY<br/>BRINGS<br/>STRENGTH ”</blockquote></aside><div className="republic-projector"><div className="holo-city"><Globe/></div><span>A STABLE REPUBLIC<br/>A SECURE GALAXY<br/>A BRIGHTER TOMORROW</span><RepublicMark/></div></>:<>
 <section className="castle-hero glass"><GlassEdge/><div className="glass-heading">Now Playing</div><button className="hero-button" data-selected={zone==="hero"} onClick={launch} disabled={!g}>{g&&<GameArt g={g} kind="hero" style={{width:"100%",height:"100%"}}/>}<div className="hero-bottom"><h1>{g?.name??"Your next adventure awaits"}</h1><span className="continue-button">▶　Continue</span><small>LAST PLAYED<br/>{g?fmtLastPlayed(g.lastPlayed):"—"}</small></div></button></section>
 <aside className="castle-status"><section className="glass profile"><GlassEdge profile/><div className="avatar"><Icon name="user" size={44}/></div><div><h2>{api.user||"Player"}</h2><span className="online">● {status.online?"Online":"Offline"}</span></div><div className="profile-bars"><strong>PLAYER</strong><div><label><span>PWR</span><span className="meter green"><i style={{width:`${(battery?.level??0)*100}%`}}/></span><output>{battery?`${Math.round(battery.level*100)} / 100`:"—"}</output></label><label><span>LIB</span><span className="meter blue"><i style={{width:"100%"}}/></span><output>{games.length} games</output></label></div></div></section><section className="glass system"><GlassEdge/><div className="glass-heading">System Status</div><button onClick={()=>openSteam("settings")}><Icon name="power" size={23}/>Battery <span>{battery?`${Math.round(battery.level*100)}%`:"—"}</span></button><button onClick={()=>openSteam("library")}><Icon name="library" size={24}/>Library <span>{games.length} games</span></button><button onClick={()=>openSteam("settings")}><Icon name="gear" size={24}/>Performance <span>Settings ›</span></button><button onClick={()=>openSteam("settings")}><Icon name="wifi" size={24}/>Network <span>{status.online?"Connected":"Offline"}</span></button></section></aside>
 <section className="castle-quick glass"><GlassEdge/><div className="glass-heading">Quick Access</div><div>{entries.slice(1).map(e=><button key={e.label} onClick={e.run}><Icon name={e.icon} size={26}/>{e.label}</button>)}</div></section><div className="castle-caption">— SWORD ART ONLINE —<small>また、見ぬ世界へ。</small></div></>}
 <section className="cinema-games"><div className="cinema-row-title">{kind==="republic"?"RECENT GAMES　←":"Recently Played"}</div><div className="cinema-row" ref={row}>{games.length?games.slice(0,60).map((game,i)=><button key={game.appid} className="cinema-game" aria-label={game.name} data-selected={selected===i} onClick={()=>{if(selected===i)launch();else{setSel(i);setZone("games");playSound("move");}}}><GameArt g={game} kind="portrait" style={{width:"100%",height:"100%"}}/><span>{game.name}</span></button>):<p>No games in this library view.</p>}</div></section>
 <footer><button onClick={options}>☰　Options</button><span>Ⓐ　SELECT　　Ⓑ　BACK</span></footer>
 </div><MenuView menu={menu} variant={kind}/></Stage></ThemeRoot>;
}

