import {CSSProperties,useEffect,useMemo,useRef,useState} from 'react';
import {GameArt,useHome,useMenu,MenuView,themeMenu} from '../common';
import {ThemeRoot,Stage,useStage,Press} from '../input';
import {openSteam,openAchievements,achievements} from '../library';
import {openDestination} from '../destinations';
import {playSound} from '../steam';
import {updateSettings} from '../settings';
import {useAssets} from '../assets';
import {MinecraftPlayer,MinecraftSkinEditor,defaultSkin} from './MinecraftPlayer';
import {MINECRAFT_CSS} from './minecraftStyles';
export function MinecraftHome(){
 const api=useHome(),{settings:s,lib:{games}}=api,{W,H}=useStage(),assets=useAssets('minecraft'),menu=useMenu();
 const [sel,setSel]=useState(0),[nav,setNav]=useState(0),[zone,setZone]=useState<'nav'|'games'|'player'>('games'),[editing,setEditing]=useState(false),[installed,setInstalled]=useState(false);
 const defaults=useMemo(defaultSkin,[]),skin=s.minecraftSkin||defaults,list=installed?games.filter(g=>g.installed):games,index=Math.min(sel,Math.max(0,list.length-1)),cur=list[index],rows=useRef<HTMLDivElement>(null);
 useEffect(()=>{rows.current?.querySelector('[data-selected=true]')?.scrollIntoView({block:'nearest',behavior:'instant'});},[index]);
 const editSkin=()=>{playSound('open');setEditing(true);};
 const options=()=>menu.open([{label:'Change Skin',action:editSkin},{label:'Player follows focus',sub:()=>[true,false].map(value=>({label:value?'On':'Off',checked:!!s.minecraftFollowFocus===value,action:()=>updateSettings({minecraftFollowFocus:value})}))},{label:'Presets',sub:()=>themeMenu()},{label:'Home Screen Settings',action:api.openSettings},{label:'Steam Home',action:api.showSteamHome}], 'Block Worlds');
 const launch=()=>cur&&api.activate(cur,()=>api.launch(cur));
 const navAction=(i:number)=>{setNav(i);if(i===0){playSound('tab');setInstalled(false);setSel(0);setZone('games');}else if(i===1){playSound('open');openDestination({place:'browser',url:'https://www.minecraft.net/'});}else if(i===2)openSteam('friends');else if(i===3)openSteam('store');else options();};
 const input=(p:Press)=>{if(p.btn==='a')window.dispatchEvent(new Event('dht-minecraft-strike'));if(menu.handle(p))return true;if(editing)return true;if(p.btn==='x'||p.btn==='menu'){options();return true;}if(p.btn==='y'){if(cur)api.nativeMenu(cur);return true;}if(p.btn==='b'){playSound('back');setZone('nav');return true;}if(p.btn==='left'){playSound('move');setZone(zone==='player'?'games':'nav');return true;}if(p.btn==='right'){playSound('move');setZone(zone==='nav'?'games':'player');return true;}if(p.btn==='up'||p.btn==='down'){playSound('move');const d=p.btn==='up'?-1:1;if(zone==='nav')setNav(i=>Math.max(0,Math.min(4,i+d)));else if(zone==='games')setSel(i=>Math.max(0,Math.min(list.length-1,i+d)));return true;}if(p.btn==='a'){if(zone==='nav')navAction(nav);else if(zone==='player')editSkin();else launch();return true;}return false;};
 const icon=(i:number)=> <span className={`mc-icon mc-icon-${i}`} aria-hidden="true"/>;
 const progress=achievements(cur);
 const scale=W/1536;
 return <ThemeRoot onInput={input} hints={{a:'Select',b:'Back',x:'Options',y:'Game Options'}}><Stage background="#2b3036"><style>{MINECRAFT_CSS}</style><div className="mc-home" style={{width:1536,height:H/scale,transform:`scale(${scale})`,'--mc-reference':`url("${assets.reference||''}")`} as CSSProperties}>
 <img className="mc-scenery" src={assets.scenery} alt=""/>
 <nav className="mc-nav">{['Play','Browser','Friends','Marketplace','Settings'].map((name,i)=><button key={name} className={nav===i?'mc-green':''} data-focus={zone==='nav'&&nav===i} onClick={()=>navAction(i)}>{i===0?<svg className="mc-nav-controller" aria-hidden="true" width="60" height="56" viewBox="0 0 60 56" shapeRendering="crispEdges"><path d="M10 8h13v3h14V8h13v4h4v7h3v12h2v17h-4v3h-8l-8-12H21L13 51H5v-3H1V31h2V19h3v-7h4Z" fill="#101114" stroke="#08090b" strokeWidth="2"/><path d="M11 12h12v3h14v-3h12v4h3v6h2v12h2v11h-5l-10-13H19L9 45H4V34h2V22h3v-6h2Z" fill="#45474c"/><path d="M12 12h11v3H12ZM37 12h12v3H37ZM9 17h3v8H9Z" fill="#777a80"/><path d="M12 21h5v5h5v5h-5v5h-5v-5H7v-5h5Z" fill="#18191c"/><path d="M13 22h3v6h5v2h-8Z" fill="#686b71"/><path d="M25 24h4v2h-4ZM32 24h4v2h-4Z" fill="#adb0b5"/><path d="M19 34h9v9h-9ZM33 34h9v9h-9Z" fill="#131416" stroke="#62656b" strokeWidth="2"/><path d="M21 36h5v5h-5ZM35 36h5v5h-5Z" fill="#35373b"/><path d="M28 29h5v5h-5Z" fill="#101113"/><path d="M43 18h5v5h-5ZM50 25h5v5h-5ZM43 32h5v5h-5ZM36 25h5v5h-5Z" fill="#16171b"/><path d="m45.5 19-1.5 3h3Z" fill="none" stroke="#72b997"/><circle cx="52.5" cy="27.5" r="1.6" fill="none" stroke="#d36f72"/><path d="m44 33 3 3m0-3-3 3" stroke="#829ccf"/><path d="M37 26h3v3h-3Z" fill="none" stroke="#ce94bd"/></svg>:icon(i)}<span>{name}</span>{nav===i&&<b>›</b>}</button>)}</nav>
 <section className="mc-worlds mc-panel"><header>{icon(0)}<h1>{installed?'Installed Games':'My Games'}</h1><button onClick={()=>openSteam('library')}><b>＋</b> Browse Library</button></header><div className="mc-world-list" ref={rows}>
 {list.map((g,i)=><article key={g.appid} className="mc-world" data-selected={i===index} data-focus={zone==='games'&&i===index}><button className="mc-row-select" onClick={()=>{playSound('select');setSel(i);setZone('games');}} aria-label={`Select ${g.name}`}><div className="mc-thumbnail"><GameArt flat g={g} kind="landscape" style={{width:'100%',height:'100%',objectFit:'cover'}}/></div><div className="mc-game-text"><strong>{g.name}</strong><span>{g.installed?'Ready to play':'In library'}</span><small>◇ &nbsp;{g.lastPlayed?new Date(g.lastPlayed*1000).toLocaleDateString():'Not played'} &nbsp;|&nbsp; {Math.round(g.playtime/60*10)/10} hrs</small></div></button><button className={`mc-play ${i===index?'mc-green':''}`} aria-label={`Play ${g.name}`} onClick={()=>api.activate(g,()=>api.launch(g))}>▶ &nbsp;Play</button><button className="mc-more" aria-label={`Options for ${g.name}`} onClick={()=>api.nativeMenu(g)}>⋮</button></article>)}
 {!list.length&&<div className="mc-empty">No games in this view.<button onClick={api.openSettings}>Library settings</button></div>}
 </div></section>
 <aside className="mc-player-panel mc-panel"><header>Player</header><div className="mc-avatar-scene"><img className="mc-avatar-bg" src={assets.scenery} alt=""/><MinecraftPlayer skin={skin} slim={s.minecraftSlim} followFocus={!!s.minecraftFollowFocus&&!editing} focusKey={`${zone}-${nav}-${index}-${menu.stack.length}`} motion={s.animations&&!api.busy&&!editing}/></div><button className="mc-change" data-focus={zone==='player'} onClick={editSkin}><svg aria-hidden="true" width="31" height="31" viewBox="0 0 32 32"><path d="M12 9a4 4 0 1 1 6 3l-2 2v4L3 26v3h26v-3l-13-8" fill="none" stroke="currentColor" strokeWidth="2.5"/></svg> Change Skin</button><button className="mc-achievements mc-inset" onClick={()=>cur&&openAchievements(cur)}><span className="mc-trophy" aria-hidden="true"/><div>Achievements<small>{progress?`${progress.unlocked}/${progress.total}`:"View progress"}</small><div className="mc-progress"><i style={{width:progress&&progress.total?`${progress.unlocked/progress.total*100}%`:0}}/></div></div></button><div className="mc-current mc-inset"><span>Selected Game</span><div>{icon(0)}<p>{cur?.name||'Your library'}<small>{cur?.installed?'Ready to play':'Choose a game'}</small></p></div></div></aside>
 <footer className="mc-footer"><span><b className="mc-a">A</b> Select</span><span><b className="mc-b">B</b> Back</span><button onClick={options}><b className="mc-x">X</b> Options</button><button onClick={()=>cur&&api.nativeMenu(cur)}><b className="mc-y">Y</b> Manage Game</button><button className="mc-profile" onClick={editSkin}>☰ &nbsp; Player Profile</button><button onClick={()=>openSteam('friends')}><svg aria-hidden="true" width="33" height="28" viewBox="0 0 32 28"><path d="M9 6h14c4 0 7 15 5 17-3 3-7-5-9-5h-6c-3 0-6 8-9 5C1 20 5 6 9 6Z" fill="#aaa" stroke="#111" strokeWidth="2"/><path d="M10 9v8M6 13h8" stroke="#222" strokeWidth="2"/><circle cx="23" cy="11" r="1.5"/><circle cx="26" cy="14" r="1.5"/></svg> &nbsp; Social</button></footer>
 {editing&&<MinecraftSkinEditor skin={skin} slim={!!s.minecraftSlim} motion={s.animations} onClose={()=>{playSound('back');setEditing(false);}} onSave={(minecraftSkin,minecraftSlim)=>{playSound('select');updateSettings({minecraftSkin,minecraftSlim});setEditing(false);}}/>}
 </div><MenuView menu={menu} variant="minecraft"/></Stage></ThemeRoot>;
}
