import {NazarickBackdrop} from "./NazarickBackdrop";
import {useState} from "react";
import {BatteryGlyph,GameArt,Icon,IconName,MenuView,themeMenu,useHome,useMenu} from "../common";
import {Press,Stage,ThemeRoot,useStage} from "../input";
import {achievements,fmtLastPlayed,fmtPlaytime,openSteam,SteamPlace} from "../library";
import {fmtTime,playSound,useBattery,useClock,useSteamStatus} from "../steam";
import {useAssets} from "../assets";

const NAV:{label:string;place:SteamPlace;icon:IconName}[]=[{label:"Home",place:"mainmenu",icon:"home"},{label:"Library",place:"library",icon:"library"},{label:"Store",place:"store",icon:"store"},{label:"Friends",place:"friends",icon:"friends"},{label:"Downloads",place:"downloads",icon:"download"},{label:"Settings",place:"settings",icon:"gear"}];

function Skull(){return <svg className="naz-skull" viewBox="0 0 32 34" aria-hidden="true"><path d="M5 15C2 2 27-2 28 13c1 7-4 7-5 12l-2 6H11l-2-6c-1-4-6-4-4-10Z" fill="#d1c4be" stroke="#635164" strokeWidth="1.2"/><path d="M7 13q6-4 7 4l-2 4-5-2Zm17 0q-6-4-7 4l2 4 5-2ZM16 20l-3 5h6Z" fill="#241529"/><path d="M11 27h10M13 26v5m3-5v5m3-5v5" stroke="#574458"/><path d="M8 8q8-5 16 0" fill="none" stroke="#eee5d4"/><path d="m3 28-2 3m27-3 3 3" stroke="#ad8a4f" strokeWidth="2"/></svg>}
function Crest(){return <svg viewBox="0 0 100 110" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="3" strokeLinejoin="round"><path d="M50 105V50M49 93C16 90 6 66 18 43L10 23l21 15-6-22 19 17M51 93c33-3 43-27 31-50l8-20-21 15 6-22-19 17M15 58l18 9-8-23 18 12M85 58l-18 9 8-23-18 12M29 79l15-2-7 11M71 79l-15-2 7 11M40 26l-5-12 11 6 4-12 4 12 11-6-5 12"/><path d="M40 31q10-9 20 0l-2 15-8 7-8-7Z" fill="currentColor"/></g><path d="m42 34 6 2-1 5-5-2Zm16 0-6 2 1 5 5-2ZM48 43h4v4h-4Z" fill="#301151"/></svg>}
export function NazarickHome(){
 const api=useHome(),{settings:s,lib:{games}}=api,{W,H}=useStage(),menu=useMenu(),assets=useAssets("nazarick"),clock=useClock(),battery=useBattery(),status=useSteamStatus();
 const [selected,setSelected]=useState(0),[zone,setZone]=useState("hero"),[nav,setNav]=useState(0);
 const index=Math.min(selected,Math.max(0,games.length-1)),game=games[index],page=Math.floor(index/7),progress=game?achievements(game):null;
 const launch=()=>{if(game)api.activate(game,()=>api.launch(game));};
 const go=(i:number)=>{setNav(i);setZone("nav");if(i===0)return;openSteam(NAV[i].place);};
 const options=()=>menu.open([{label:"Presets",sub:()=>themeMenu()},{label:"Home Screen Settings",action:api.openSettings}],"Nazarick System");
 const input=(p:Press)=>{if(menu.handle(p))return true;if(p.btn==="l1"||p.btn==="r1"){go(p.btn==="r1"?1:5);return true;}if(p.btn==="x"||p.btn==="menu"){options();return true;}if(p.btn==="y"){if(game)api.nativeMenu(game);return true;}if(p.btn==="b"){setZone("nav");setNav(0);return true;}if(p.btn==="a"){zone==="nav"?go(nav):launch();return true;}if(p.btn==="up"){setZone(zone==="recent"?"hero":"nav");return true;}if(p.btn==="down"){setZone(zone==="nav"?"hero":"recent");return true;}if(p.btn==="left"||p.btn==="right"){const d=p.btn==="left"?-1:1;if(zone==="nav")setNav(i=>Math.max(0,Math.min(5,i+d)));else {setZone("recent");setSelected(i=>Math.max(0,Math.min(games.length-1,i+d)));}playSound("move");return true;}return false;};
 return <ThemeRoot onInput={input} hints={{a:"Select",b:"Back",x:"Options",y:"Game options"}}><Stage background="#08060c"><div className="naz-home" data-motion={s.animations&&!api.busy} style={{transform:`scale(${W/1536},${H/864})`}}><NazarickBackdrop motion={s.animations&&!api.busy}/>
 <header className="naz-top"><button className="naz-profile" onClick={()=>go(3)}><span className="naz-profile-seal" style={assets.home?{backgroundImage:`url("${assets.home}")`,backgroundSize:"980px auto",backgroundPosition:"60% 16%"}:undefined}>{!assets.home&&<Crest/>}</span><span>{api.user||"Ainz Ooal Gown"}<small>Supreme Ruler of Nazarick</small><small className="naz-online">● {status.online?"Online":"Offline"}</small></span></button><nav>{NAV.map((n,i)=><button key={n.label} data-focus={zone==="nav"&&nav===i} data-active={i===0} onFocus={()=>{setZone("nav");setNav(i);}} onClick={()=>go(i)}>{n.label}</button>)}</nav><div className="naz-status"><button aria-label="Search library" onClick={()=>openSteam("search")}><Icon name="search" size={22}/></button><Icon name={status.online?"wifi":"network"} size={23}/>{battery&&<span><BatteryGlyph level={battery.level} charging={battery.charging} w={30}/> {Math.round(battery.level*100)}%</span>}<time>{fmtTime(clock,s.clock24)}</time></div></header>
 <aside className="naz-left"><h1>NAZARICK<small>SYSTEM</small></h1><div className="naz-wheel" data-art={!!assets.wheel}>{assets.wheel?<img className="naz-wheel-art" src={assets.wheel} alt=""/>:<><div className="naz-wheel-runes"/><div className="naz-wheel-core"><Crest/></div></>}{[{label:"Play",icon:"play",i:0,x:50,y:12},{label:"Library",icon:"library",i:1,x:17,y:32},{label:"Store",icon:"store",i:2,x:83,y:32},{label:"Friends",icon:"friends",i:3,x:20,y:73},{label:"Settings",icon:"gear",i:5,x:80,y:73}].map(n=><button key={n.label} style={{left:`${assets.wheel?({Play:50,Library:23,Store:77,Friends:25,Settings:74}[n.label]):n.x}%`,top:`${assets.wheel?({Play:23,Library:37,Store:37,Friends: 70,Settings: 70}[n.label]):n.y}%`}} aria-label={n.label} onClick={()=>n.i===0?launch():go(n.i)}><Icon name={n.icon as IconName} size={32}/><span>{n.label}</span></button>)}</div><div className="naz-motto naz-frame">ALL LIFE IS A PART<br/>OF MY COLLECTION</div></aside>
 <blockquote className="naz-quote naz-frame">All of reality…<br/>is but a game.<small>— Ainz Ooal Gown</small></blockquote>
 <section className="naz-feature naz-frame" aria-label="Featured game">{game?<><div className="naz-feature-art" key={game.appid}><GameArt flat g={game} kind="hero" style={{width:"100%",height:"100%",objectFit:"cover"}}/></div><div className="naz-feature-shade"/><p className="naz-eyebrow">FEATURED</p><GameArt flat g={game} kind="logo" style={{position:"absolute",left:35,top:48,width:490,height:108,objectFit:"contain",objectPosition:"left center"}}/><div className="naz-feature-info"><button className="naz-play" data-focus={zone==="hero"} onClick={launch}><Icon name="play" size={25}/>Play</button><span><small>LAST PLAYED</small>{fmtLastPlayed(game.lastPlayed)}</span><span><small>PLAY TIME</small>{fmtPlaytime(game.playtime)}</span><span><small>ACHIEVEMENTS</small>{progress?`${progress.unlocked}/${progress.total}`:"—"}<meter min={0} max={progress?.total||1} value={progress?.unlocked||0}/></span></div></>:<div className="naz-empty">Your library awaits.<button onClick={api.openSettings}>Choose library source</button></div>}</section>
 <section className="naz-recent naz-frame"><h2><Skull/>Recently Played</h2><div className="naz-games" key={page}>{games.slice(page*7,page*7+7).map((g,i)=><button key={g.appid} aria-label={`Play ${g.name}`} data-focus={index===page*7+i} onFocus={()=>{setSelected(page*7+i);setZone("recent");}} onMouseEnter={()=>{setSelected(page*7+i);setZone("recent");}} onClick={()=>api.activate(g,()=>api.launch(g))}><GameArt flat g={g} kind="portrait" style={{width:"100%",height:142,objectFit:"cover"}}/><span>{fmtPlaytime(g.playtime)}</span></button>)}</div></section>
 <aside className="naz-right"><section className="naz-now naz-frame"><h2><Skull/>Selected Game</h2>{game&&<button onClick={launch}><GameArt flat g={game} kind="portrait" style={{width:88,height:92,objectFit:"cover"}}/><span>{game.name}<small>{game.installed?"● Installed":"In library"}</small></span><Icon name="play" size={22}/></button>}</section><section className="naz-terminal naz-frame"><h2>✦ Nazarick Terminal</h2>{[{...NAV[1],label:"View Full Library"},NAV[4],{...NAV[3],label:"Friends & Chat"},{...NAV[2],label:"Browse Store"},{...NAV[5],label:"System Settings"}].map(n=><button key={n.label} onClick={()=>openSteam(n.place)}><Icon name={n.icon} size={24}/>{n.label}</button>)}</section></aside>
 <footer className="naz-footer"><span>⌛ <small>{games.length} games in your collection</small></span><b>✧　 SUPREME BEING · NAZARICK · THE GREAT TOMB　 ✧</b><span>Ⓐ SELECT　 Ⓑ BACK　 ☰ OPTIONS</span></footer>
 </div><MenuView menu={menu} variant="nazarick"/></Stage></ThemeRoot>;
}
