export const PAIN_CSS=`
.pain-home{position:absolute;inset:0;width:1280px;height:800px;transform-origin:0 0;background:#0b0912 center/100% 100% no-repeat;color:#c49ae8;font-family:Arial,sans-serif;overflow:hidden}
.pain-home *{box-sizing:border-box}.pain-home button{font:inherit;color:inherit;cursor:pointer;border:0;background:none;padding:0}.pain-home button:focus-visible{outline:2px solid #e0beff;outline-offset:4px}.pain-home button:disabled{opacity:.3;cursor:default}
.pain-top{position:absolute;top:12px;left:28px;right:23px;display:flex;align-items:center;justify-content:space-between;height:43px}.pain-brand{display:flex;align-items:center;gap:10px;color:#ab75e6}.pain-brand>span{font-size:12px;letter-spacing:2px;color:#78648d}.pain-brand b{color:#b382dc}.pain-brand i{width:92px;height:1px;background:#8c58bf;margin-left:4px}.pain-status{display:flex;align-items:center;gap:25px;font-size:12px;letter-spacing:2px}.pain-status>span{display:flex;align-items:center;gap:4px}.pain-avatar{position:relative;width:36px;height:36px;border:1px solid #8752ac!important;background:#24112d!important}.pain-avatar img{width:100%;height:100%;object-fit:cover}.pain-avatar i{position:absolute;width:10px;height:10px;border-radius:50%;right:-5px;bottom:-5px;background:#777}.pain-avatar i[data-online=true]{background:#49b85f}
.pain-inscription{position:absolute;left:64px;top:89px;color:#8e55c2}.pain-inscription>div{display:flex;gap:8px}.pain-inscription strong{font-size:43px;font-family:serif;writing-mode:vertical-rl;line-height:1}.pain-inscription small{font-size:20px;writing-mode:vertical-rl;letter-spacing:6px}.pain-inscription>span{display:block;margin-top:10px;font-size:9px;line-height:1.3;letter-spacing:1px;color:#74607d}.pain-quote{position:absolute;right:24px;top:96px;text-align:right;color:#9476ae}.pain-quote>div{writing-mode:vertical-rl;font-size:15px;letter-spacing:4px;line-height:1.8;margin-left:auto;font-family:serif}.pain-quote small{display:block;font-size:9px;letter-spacing:.8px;line-height:1.4;margin-top:14px;color:#74617f}
.pain-feature{position:absolute;left:49px;top:151px;width:510px;height:470px}.pain-orbits{position:absolute;inset:0;width:100%;height:100%;overflow:visible;pointer-events:none;fill:none;stroke:#8050b577;stroke-width:1}.pain-orbits .pain-orbit-light{stroke:#c485ff;stroke-width:2;filter:drop-shadow(0 0 4px #bb68ff) drop-shadow(0 0 11px #9342ff)}.pain-orbits g{fill:#110b1b;stroke:#7e4aa8}.pain-orbits .pain-orbit-symbol{fill:none;stroke:#c38be9;stroke-width:1.25;stroke-linecap:round;stroke-linejoin:round;filter:drop-shadow(0 0 2px #934ad5)}.pain-orbits text{fill:#9f67ca;stroke:none;font:22px serif;text-anchor:middle}.pain-feature-disc{position:absolute;left:35px;top:36px;width:440px;height:400px;border-radius:50%;overflow:hidden;border:1px solid #8154a855;background:#07090d;box-shadow:0 0 0 6px #100c18aa,0 0 35px #0007}.pain-feature-art{position:absolute;inset:0}.pain-feature-shade{position:absolute;inset:0;background:linear-gradient(#03040866,transparent 40%,#02050922 58%,#05060ade 88%)}.pain-eyebrow{position:absolute;top:11px;left:0;right:0;text-align:center;font-size:10px;letter-spacing:3px;color:#ac7fe3}.pain-feature-logo{position:absolute;top:60px;left:57px;width:326px;height:72px}.pain-feature-name{position:absolute;left:58px;right:50px;bottom:90px}.pain-feature-name strong{display:block;font-size:17px;letter-spacing:1px;white-space:nowrap;text-overflow:ellipsis;overflow:hidden}.pain-feature-name small{display:block;font-size:10px;letter-spacing:2px;margin-top:7px;color:#9864c7}.pain-feature-name b{font-weight:normal;color:#c69ee6}.pain-feature-actions{position:absolute;bottom:32px;left:94px;display:flex;align-items:center;gap:13px}.pain-feature-actions>button:first-child{border:1px solid #bb7ce8;border-radius:28px;display:flex;align-items:center;justify-content:center;gap:24px;width:204px;height:42px;background:#0a0611b3;letter-spacing:1.4px;font-size:14px;box-shadow:inset 0 0 8px #9448d033,0 0 10px #b460ef66}.pain-feature-actions>button:last-child{width:36px;height:36px;border-radius:50%;border:1px solid #7c4cac77;display:grid;place-items:center}.pain-feature-actions [data-focus=true]{box-shadow:0 0 0 2px #d39aff,0 0 18px #b96dff!important;background:#65309977!important}
.pain-recent,.pain-installed{position:absolute;left:570px;width:620px}.pain-recent{top:297px}.pain-installed{top:513px}.pain-home h2{font-size:12px;font-weight:normal;letter-spacing:4px;margin:0 0 14px 2px;color:#d0b1ed}.pain-recent-row{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.pain-installed-row{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.pain-card{position:relative;border:1px solid #75528566!important;overflow:hidden;border-radius:5px;height:165px;box-shadow:0 3px 10px #0007}.pain-installed .pain-card{height:86px}.pain-card img{display:block}.pain-card[data-selected=true]{border-color:#ab69ef!important;box-shadow:0 0 3px 1px #886cf0,0 0 10px #446ef180}.pain-card[data-focus=true]{transform:translateY(-3px);box-shadow:0 0 0 2px #d5a6ff,0 0 19px #a35fe9b0}.pain-star{position:absolute;bottom:3px;left:4px;width:15px;height:15px;line-height:13px;text-align:center;font-size:12px;border:1px solid #9870c1;border-radius:50%;background:#0d0817}.pain-next{position:absolute;right:-64px;top:95px;width:43px;height:43px;border:1px solid #8653b855!important;border-radius:50%;font-size:31px!important;background:#0d0815aa!important}.pain-no-games{font-size:15px;color:#c4b1d4;padding:25px 0}.pain-empty{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:20px}.pain-empty button{border:1px solid #9961bc;padding:10px;border-radius:22px}
.pain-nav{position:absolute;left:298px;top:672px;height:101px;display:flex;gap:45px}.pain-nav:after{content:"";width:87px;height:1px;background:#8050a4;position:absolute;left:614px;top:43px}.pain-nav>button{width:73px;display:flex;align-items:center;flex-direction:column;gap:14px;position:relative}.pain-nav>button>span{height:65px;width:65px;border:1px solid #71449899;border-radius:50%;display:grid;place-items:center;background:#09080d8c}.pain-nav b{text-transform:uppercase;font-weight:normal;font-size:11px;letter-spacing:1px}.pain-nav [data-selected=true]>span{border:2px solid #c698ff;color:#e7ccff;box-shadow:inset 0 0 11px #bc6dff,0 0 9px #d3a4ff,0 0 24px #aa54df;background:#42215e66}.pain-nav [data-selected=true]:before{content:"";position:absolute;left:-12px;top:-12px;width:97px;height:90px;border:1px solid #8556a866;border-radius:50%;box-shadow:0 0 0 5px #9453c51a}.pain-nav [data-focus=true] b{text-shadow:0 0 8px #d998ff;color:#e6c4ff}
.pain-home[data-motion=true] .pain-card,.pain-home[data-motion=true] .pain-nav span,.pain-home[data-motion=true] .pain-feature-actions button{transition:transform 240ms cubic-bezier(.2,.8,.2,1),box-shadow 240ms ease,background 240ms ease}.pain-home[data-motion=true] .pain-recent-row,.pain-home[data-motion=true] .pain-installed-row{animation:pain-row-in 330ms cubic-bezier(.2,.8,.2,1)}.pain-home[data-motion=true] .pain-orbit-light{animation:pain-orbit 24s linear infinite}.pain-home[data-motion=true]{animation:pain-enter 500ms ease-out}.dht-menu--pain{animation:pain-enter 230ms ease-out}
@keyframes pain-orbit{to{stroke-dashoffset:-100}}@keyframes pain-row-in{from{opacity:0;transform:translateX(14px)}to{opacity:1;transform:translateX(0)}}@keyframes pain-enter{from{opacity:0}to{opacity:1}}
@media(prefers-reduced-motion:reduce){.pain-home *,.pain-home,.dht-menu--pain{animation:none!important;transition:none!important}}

.pain-home:before{content:"";position:absolute;inset:0;background:#03010826;pointer-events:none}
.pain-nav{left:312px}.pain-installed h2{margin-bottom:9px}
.dht-destination[data-theme=pain],.dht-store[data-dht-store-skin=pain]{animation:pain-page-in 300ms cubic-bezier(.2,.8,.2,1)}
@keyframes pain-page-in{from{opacity:0;translate:0 10px}to{opacity:1;translate:0 0}}
@media(prefers-reduced-motion:reduce){.dht-destination[data-theme=pain],.dht-store[data-dht-store-skin=pain]{animation:none!important}}

.pain-home[data-motion=true] .pain-feature-art{animation:pain-feature-change 320ms ease-out}
@keyframes pain-feature-change{from{opacity:.25;transform:scale(1.035)}to{opacity:1;transform:scale(1)}}

.pain-logo-name{display:flex;align-items:center;justify-content:center;width:100%;height:100%;color:#e5c7ff;font-size:34px;font-weight:600;line-height:1.15;text-align:center;text-wrap:balance;background:none;overflow-wrap:anywhere}
`;
