/** Shared launch lifecycle, distinct visual language for every preset. */
export const LAUNCH_CSS = String.raw`
.dht-launch{--launch-color:#d5eaff;--launch-glass:#080c18dc;font-family:Arial,sans-serif;overflow:hidden}
.dht-launch-panel{border:1px solid #ffffff26;background:var(--launch-glass);box-shadow:0 20px 80px #0008;max-width:900px;box-sizing:border-box}
.dht-launch h1{margin:12px 0;color:var(--launch-color)}
.dht-launch button{font-family:inherit;border-color:var(--launch-color)!important;background:#080c18bb!important;color:var(--launch-color)!important}
.dht-launch-loader{position:relative;width:62px;height:62px;margin:24px auto;box-sizing:border-box;border:3px solid #ffffff20;border-top-color:var(--launch-color);border-radius:50%;animation:launchSpin 1.3s linear infinite}
.dht-launch[data-console=vita]{--launch-color:#72ddff;--launch-glass:#0755aacc}.dht-launch[data-console=vita] .dht-launch-panel{border-radius:50px;background:linear-gradient(150deg,#1376cedd,#063e84dd)}
.dht-launch[data-console=vita] .dht-launch-loader{border:1px solid #a3efff;background:radial-gradient(ellipse at 50% 85%,#c4faffb0,transparent 45%),radial-gradient(circle at 35% 25%,#ffffff99,#41b5ed66 40%,#003595);box-shadow:0 0 18px #66caff99;animation:launchBreathe 1.8s ease-in-out infinite alternate}
.dht-launch[data-console=ps2]{--launch-color:#719cff;--launch-glass:#000d}.dht-launch[data-console=ps2] .dht-launch-panel{border:0;box-shadow:none}.dht-launch[data-console=ps2] .dht-launch-loader{border:0;animation:launchSpin 4s linear infinite}.dht-launch[data-console=ps2] .dht-launch-loader i{position:absolute;width:17px;height:17px;background:linear-gradient(135deg,#e7f8ff,#2770eb);box-shadow:0 0 14px #377dff}.dht-launch[data-console=ps2] i:nth-child(2){right:0}.dht-launch[data-console=ps2] i:nth-child(3){bottom:0}.dht-launch[data-console=ps2] i:nth-child(4){bottom:0;right:0}
.dht-launch[data-console=ps3],.dht-launch[data-console=psp]{--launch-glass:#111319c9}.dht-launch[data-console=ps3] .dht-launch-panel,.dht-launch[data-console=psp] .dht-launch-panel{border:0;box-shadow:none;background:linear-gradient(90deg,transparent,#15151be8,transparent);text-shadow:0 2px 4px #000}.dht-launch[data-console=ps3] .dht-launch-loader,.dht-launch[data-console=psp] .dht-launch-loader{width:230px;height:4px;border:0;border-radius:0;background:#ffffff25;overflow:hidden;animation:none}.dht-launch[data-console=ps3] .dht-launch-loader i:first-child,.dht-launch[data-console=psp] .dht-launch-loader i:first-child{display:block;width:35%;height:100%;background:linear-gradient(90deg,transparent,#fff,transparent);animation:launchBar 1.4s ease-in-out infinite alternate}
.dht-launch[data-console=ps4]{--launch-color:#bdeaff;--launch-glass:#003785db}.dht-launch[data-console=ps4] .dht-launch-panel{border:0;border-left:4px solid #70ccff;background:linear-gradient(120deg,#005cbbc9,#001b5de8)}
.dht-launch[data-console=ps5]{--launch-color:#fff;--launch-glass:#17191dd9}.dht-launch[data-console=ps5] .dht-launch-panel{border-radius:22px;border-color:#ffffff60}.dht-launch[data-console=ps5] .dht-launch-loader{border-width:2px;border-top-color:#fff;border-bottom-color:#a99665}
.dht-launch[data-console=xbox]{--launch-color:#aeff00;--launch-glass:#001400eb;font-family:monospace}.dht-launch[data-console=xbox] .dht-launch-panel{border:2px solid #528719;clip-path:polygon(3% 0,97% 0,100% 6%,100% 94%,97% 100%,3% 100%,0 94%,0 6%)}.dht-launch[data-console=xbox] .dht-launch-loader{background:radial-gradient(#e8ff82,#69c600 40%,#092600 65%);border:2px solid #9ff900;box-shadow:0 0 30px #79f90080,inset 0 0 14px #cfff00;animation:launchBreathe 1.5s ease-in-out infinite alternate}
.dht-launch[data-console=x360]{--launch-color:#a1e34a;--launch-glass:#263027eb}.dht-launch[data-console=x360] .dht-launch-loader{border-style:dotted;border-width:6px}.dht-launch[data-console=x360][data-variant=blades] .dht-launch-panel{border-radius:60px 12px 60px 12px;border:3px solid #a9aaa7;background:linear-gradient(110deg,#435322ef,#a3b14be8,#384621ef)}.dht-launch[data-console=x360][data-variant=nxe] .dht-launch-panel{border-radius:16px;background:linear-gradient(#e8ece8ee,#b8c2b9ee);color:#233122}.dht-launch[data-console=x360][data-variant=nxe]{--launch-color:#376d12}.dht-launch[data-console=x360][data-variant=kinect] .dht-launch-panel{border-radius:0;background:#edf1edeb;color:#304629}.dht-launch[data-console=x360][data-variant=kinect]{--launch-color:#397600}.dht-launch[data-console=x360][data-variant=metro] .dht-launch-panel{border:0;border-left:14px solid #73b829;background:#202520ec}
.dht-launch[data-console=aero],.dht-launch[data-console=aero2]{--launch-color:#d5ff35;--launch-glass:#0055c6d9}.dht-launch[data-console=aero] .dht-launch-panel,.dht-launch[data-console=aero2] .dht-launch-panel{border-radius:70px 45px;border:2px solid #abedff;box-shadow:inset 0 4px 8px #b9ecffbb,inset 0 -8px 20px #0040b6,0 0 25px #3fafff77;background:linear-gradient(150deg,#63caffd9,#0868d9ee 22%,#003dafed)}.dht-launch[data-console=aero] .dht-launch-loader,.dht-launch[data-console=aero2] .dht-launch-loader{width:220px;height:20px;border:2px solid #d2edff;overflow:hidden;border-radius:20px;background:#00205d;animation:none}.dht-launch[data-console=aero] .dht-launch-loader i:first-child,.dht-launch[data-console=aero2] .dht-launch-loader i:first-child{display:block;height:100%;width:35%;background:linear-gradient(#ecffb2,#9de300 50%,#67b900);border-radius:20px;animation:launchBar 1.5s ease-in-out infinite alternate}
.dht-launch[data-console=dial]{--launch-color:#85ff00;--launch-glass:#050a06ed}.dht-launch[data-console=dial][data-variant=crimson]{--launch-color:#ff344e}.dht-launch[data-console=dial][data-variant=arctic]{--launch-color:#42ddff}.dht-launch[data-console=dial] .dht-launch-panel{border-radius:40px;border-color:var(--launch-color)}.dht-launch[data-console=dial] .dht-launch-loader{border-color:var(--launch-color);box-shadow:0 0 18px color-mix(in srgb,var(--launch-color) 45%,transparent);animation:launchBreathe 1s ease-in-out infinite alternate}.dht-launch[data-console=dial] .dht-launch-loader:after{content:'';position:absolute;inset:9px;background:var(--launch-color);clip-path:polygon(0 0,100% 0,65% 50%,100% 100%,0 100%,35% 50%)}
.dht-launch[data-console=castle]{--launch-color:#546c85;--launch-glass:#eaf6ffe3;font-family:Cardinal,sans-serif}.dht-launch[data-console=castle] .dht-launch-panel{color:#4d637b;border:2px solid #fff;clip-path:polygon(2% 0,98% 0,100% 5%,100% 95%,98% 100%,2% 100%,0 95%,0 5%);box-shadow:inset 0 0 30px #fff}.dht-launch[data-console=castle] .dht-launch-loader{border-color:#8bb5d333;border-top-color:#f2c500;border-right-color:#f2c500}
.dht-launch[data-console=republic]{--launch-color:#d5b67b;--launch-glass:#060d15e8;font-family:AurebeshEnglish,Georgia,serif}.dht-launch[data-console=republic] .dht-launch-panel{border:3px double #ac8750;background:repeating-linear-gradient(0deg,#59baff05 0 1px,transparent 1px 4px),#040b14e8}.dht-launch[data-console=republic] .dht-launch-loader{border-style:dashed;box-shadow:0 0 18px #cea25333}
.dht-launch[data-console=minecraft]{--launch-color:#b5ec8a;--launch-glass:#292b2df5;font-family:BlockWorlds,monospace}.dht-launch[data-console=minecraft] .dht-launch-panel{border:4px solid #101112;box-shadow:inset 3px 3px #85878a,inset -3px -3px #050505}.dht-launch[data-console=minecraft] button{border-radius:0!important;box-shadow:inset 2px 2px #939a8c,inset -2px -2px #000}.dht-launch[data-console=minecraft] .dht-launch-loader{width:240px;height:18px;border:3px solid #111;border-radius:0;background:#555;animation:none;overflow:hidden;box-shadow:0 0 0 1px #aaa}.dht-launch[data-console=minecraft] .dht-launch-loader i:first-child{display:block;width:35%;height:100%;background:repeating-linear-gradient(90deg,#80bb48 0 9px,#619331 9px 12px);animation:launchBar 2s steps(12) infinite alternate}
.dht-launch[data-console=pain],.dht-launch[data-console=nazarick]{--launch-color:#c792ff;--launch-glass:#0b0515e8;font-family:Georgia,serif}.dht-launch[data-console=pain] .dht-launch-panel{border-radius:45px;border-color:#6d438f}.dht-launch[data-console=pain] .dht-launch-loader{box-shadow:0 0 0 7px #8b49bb33,0 0 0 13px #9f5bc822,0 0 25px #974dfc55;border-left-color:#b876f0}.dht-launch[data-console=nazarick] .dht-launch-panel{border:4px double #b6975e;box-shadow:inset 0 0 0 7px #08050e,inset 0 0 0 8px #816038,0 10px 60px #000}.dht-launch[data-console=nazarick] .dht-launch-loader{border-color:#95713c;border-top-color:#cf9eff;box-shadow:0 0 15px #ac61fa55}.dht-launch[data-console=nazarick] .dht-launch-loader:after{content:'✦';position:absolute;inset:0;display:grid;place-items:center;font-size:35px;color:#d5b479}
.dht-launch[data-console=x360][data-variant=nxe] button,.dht-launch[data-console=x360][data-variant=kinect] button{background:#edf3e8!important;color:#315500!important}.dht-launch[data-console=castle] button{background:#ffdc38!important;color:#304b64!important}
.dht-launch[data-motion=false] *{animation:none!important}@media(prefers-reduced-motion:reduce){.dht-launch *{animation:none!important}}
@keyframes launchSpin{to{transform:rotate(360deg)}}@keyframes launchBar{to{transform:translateX(190%)}}@keyframes launchBreathe{to{transform:scale(.92);filter:brightness(1.3)}}
`;
